version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8888"
    container_name : nmap-1.5
    volumes :
      - .:/fam_pay_test
    ports:
      - "8888-8888"
